version: '3.8'

services:
  db:
    image: postgres:16
    container_name: equiledger_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7iron-hide
      POSTGRES_DB: equiledger
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: equiledger_app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 7iron-hide
      DB_NAME: equiledger
      DB_PORT: 5432
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

volumes:
  db-data:
